site_name: Heracles' LFS Ground Base Documentation
nav:
  - 'LFS Ground Base Documentation': index.md
  - 'Overview': overview.md
  - 'Features': features.md
  - 'Frequently Asked Questions': faq.md
  - 'Developer Documentation':
    - 'Code Overview': code_overview.md
    - 'Shared Lua': shared_lua.md
    - 'Serverside Lua':
      - 'Overridable Functions': overridable_server_functions.md
    - 'Clientside Lua':
        - 'Overridable Functions': overridable_client_functions.md
    - 'Debugging': debugging.md
  - 'Breaking Changes': breaking_changes.md
theme:
  name: material
  palette:
    scheme: slate
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share

repo_url: https://github.com/ianespana/lfs_ground_base
repo_name: ianespana/lfs_ground_base